config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
      collection do
        get 'search'
      end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません'
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user

  def show_first_group_user
    first_group_user = group_user.first.created_at
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :content, presence: true,unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit,:update]

def index
end

def new
  @group = Group.new
  @group.users << current_user
end

def create
  @group = Group.new(group_params)
  if @group.save
    redirect_to root_path, notice: "グループが作成されました"
  else
    render :new
  end
end

def update
  if @group.update(group_params)
    redirect_to group_messages_path(@group),notice: "グループを編集しました"
  else
    render :edit
  end
end

def search
  if params[:group_id].present?
    @group = Group.find(params[:group_id])
    @ids = @group.users.ids
    @users = User.where.not(id: @ids).where('name LIKE(?)', "#{params[:keyword]}%").limit(20)
  else
    @users = User.where.not(id:current_user.id).where('name LIKE(?)', "#{params[:keyword]}%").limit(20)
  end
  respond_to do|format|
    format.json
  end
end

private

def group_params
  params.require(:group).permit(:name, { :user_ids => [] })
end

def set_group
  @group=Group.find(params[:id])
end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :set_group_date

def index
  @message=Message.new
  @messages=@group.messages.includes(:user)
  respond_to do |format|
    format.html
    format.json{ @new_message = @messages.where('id > ?', params[:message][:id]) }
  end
end

def create
  @message=@group.messages.create(message_params)
    respond_to do |format|
      format.html { redirect_to group_messages_path(@group), notice: "html" }
      format.json
    end
end

private

def message_params
  params.require(:message).permit(:content, :image).merge(user_id:current_user.id)
end

def set_group_date
  @group=Group.find(params[:group_id])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
end

def edit
end

def update
  if current_user.update(user_params)
    redirect_to root_path
  else
    render :edit
  end
end

private

def user_params
  params.require(:user).permit(:name, :email)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  -if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - group.errors.full_messages.each do|message|
          %li= message

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.hidden_field :id, class: "chat_group_id", value:group.id
      = f.text_field :name,class: "chat_group_name chat-group-form__input", placeholder: "グループ名を入力してください"

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :メンバー追加,class: "chat-group-form__label",id: "chat_group"
    .chat-group-form__field--right
      %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください",name: "keyword"}
      .user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー,class: "chat-group-form__label",for: "chat_group_チャットメンバー"
    .chat-group-form__field--right
      #chat-group-users
      - @group.users.each do|member|
        #chat-group-user-child.chat-group-user.clearfix.js-chat-member
          %input{:name => "group[user_ids][]", :type => "hidden", :value => "#{current_user.id}"}
          %p.chat-group-user__name
            = member.name
          %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
 %h1 チャットグループ編集
 = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.contents__left

 .contents__left--top
  %h3.contents__left--top_user_name
   = current_user.name
  = link_to edit_user_path(current_user) do
   .contents__left--top_icon
    = fa_icon "cog",class: 'icon'
  = link_to new_group_path do
   .contents__left--top_icon
    = fa_icon "edit",class: 'icon'

 .contents__left--main
  - current_user.groups.each do|group|
   .contents__left__main_room
    = link_to group_messages_path(group) do
     .contents__left--main_room_name
      = group.name
     .contents__left--main_room_message
      hello

app/views/groups/new.html.haml
.chat-group-form
 %h1 新規チャットグループ
 = render partial: 'form', locals: { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset: UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.4.2/css/all.css", integrity: "sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns", rel: "stylesheet"}
  %body
    - flash.each do |key, value|
      = content_tag(:div, value, class: key )
    = yield

app/views/messages/_message.html.haml
%li.contents__right--main__message_wrapper{"data-message-id": "#{message.id}"}
 .contents__right--main__message_name
  = message.user.name
 .contents__right--main__message_day
  = message.created_at.to_s(:published_on)
 .contents__right--main__message_text
  - if message.content.present?
   = message.content
 .contents__right--main__message_image
  = image_tag message.image.url, class: 'contents__right--main__message_image' if message.image.present?

app/views/messages/_side_bar.html.haml
.contents__left

 .contents__left--top
  %h3.contents__left--top_user_name
   = current_user.name
  = link_to edit_user_path(current_user) do
   .contents__left--top_icon
    = fa_icon "cog",class: 'icon'
  = link_to new_group_path,data:{"turbolinks"=>false} do
   .contents__left--top_icon
    = fa_icon "edit",class: 'icon'

 .contents__left--main
  - current_user.groups.each do|group|
   .contents__left__main_room
    = link_to group_messages_path(group) do
     .contents__left--main_room_name
      = group.name
     .contents__left--main_room_message
      = group.show_last_message

app/views/messages/index.html.haml
.contents
 = render 'side_bar'

 .contents__right
  .contents__right--top
   .contents__right--top_room
    .contents__right--top_room_name
     = @group.name
    = link_to edit_group_path(@group),data:{"turbolinks"=>false} do
     .contents__right--top_room_button edit

  .contents__right--main#scroll
   .contents__right--main__room_wrapper
    .contents__right--main__room_member MEMBER :
    - @group.users.each do|member|
     .contents__right--main__room_name
      = member.name

   %ul.contents__right--main__message
    = render @messages

  .contents__right--bottom
   = form_for [@group,@message] ,html:{id:'new_comment'} do |f|
    = f.text_field :content, placeholder: "message!", class: 'input'
    .contents__right--bottom_icon
     %label
      = f.file_field :image, class: "image_file_select"
      = fa_icon("file-image-o")
    = f.submit 'SEND', class: "contents__right--bottom_submit"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'